export type TNavigateMode =
  | 'login'
  | 'inventory'
  | 'woodcutting'
  | 'mining'
  | 'fishing'
  | 'alchemy'
  | 'smelting'
  | 'cooking'
  | 'forge'
  | 'shadow-mastery'
  | 'market'
  | 'vendor'
  | 'battle'
  | 'pets'
  | 'guilds'
